#!/bin/bash

alias top10="du -sm * | sort -k 1 -n -r | head -10"

# Convenience stuff
alias start=open
alias goog="open http://www.google.com/"

alias ssh="ssh -A"    # agent forwarding

# Mac specific stuff
alias mtr="sudo mtr --curses"   # by default Mac doesn't have 
alias ia="open -a \"iA Writer\""
alias flushdns="dscacheutil -flushcache"

# Editing
alias vi="vim"

function vin {
    d="~/notes"
    pushd $d
    vi $1
    echo "---> that was just stored in $d"
    popd
}

# My hosts
alias xenon="ssh -A sef@xenon.stanford.edu"
alias dreamhost="ssh -A sefklon@sef.kloninger.com"

# Class2go Project

if [ -r ~/src/class2go/tools/bash_aliases ]; then
    . ~/src/class2go/tools/bash_aliases
fi

function server() {
	local port="${1:-9000}"
	open "http://localhost:${port}/"
	python -m SimpleHTTPServer "$port"
}
