#!/bin/bash

alias top10="du -sm * | sort -k 1 -n -r | head -10"
alias ll="ls -ltrh"

# Convenience stuff
alias start=open
alias goog="open http://www.google.com/"

alias ssh="ssh -A"    # agent forwarding

# Mac specific stuff
alias mtr="sudo mtr --curses"   # by default Mac doesn't have 
alias ia="open -a \"iA Writer\""
alias flushdns="dscacheutil -flushcache"
alias ip="ipython"

# Editing
alias vi="vim"

function vin {
    d="~/notes"
    pushd $d
    vi $1
    echo "---> that was just stored in $d"
    popd
}

# My hosts
alias xenon="ssh -A sef@xenon.stanford.edu"
alias corn="ssh -A sef@corn.stanford.edu"
alias dreamhost="ssh -A sefklon@sef.kloninger.com"

function source_if_exists {
    if [ -f $1 ]; then
        source $1
    fi
}


# Class2Go Project
source_if_exists ~/src/class2go/tools/bash_aliases
source_if_exists ~/src/class2go/tools/bash_aliases.sh
source_if_exists ~/src/class2go/tools/bash_bug_reports
source_if_exists ~/src/class2go/tools/bash_bug_reports.sh
alias tests="REUSE_DB=1 ./manage.py test -v 2 --attr='!selenium'"
alias tests-full="./manage.py test -v 2 --attr='!selenium'"

function server() {
	local port="${1:-9000}"
	open "http://localhost:${port}/"
	python -m SimpleHTTPServer "$port"
}

function m() {
    if [ -d  ~/src/class2go/main ]; then
        cd ~/src/class2go/main
    elif [ -d ~/class2go/main ]; then
        cd ~/class2go/main
    else
        echo "hrm, not here"
    fi
}

function mdview() {
    if [ $# != 1 ]; then
        echo "usage: mdview file.md"
        return 1
    fi

    input=$1
    base=${input%.md}
    if [ $input == $base ]; then
        echo "error, \"${input}\" needs to have .md extension"
        return 1
    fi
    new=/tmp/${base}.html
    if [ -f $new ]; then
        read -p "Careful, \"${new}\" already exists, clobber? (y/n): " confirm
        if [[ ! $confirm =~ ^[Yy] ]]; then
            return 1
        fi
        rm $new
    fi
    markdown $input > $new
    open $new       # not portable, works on Mac
    return 0
}


function e2date() {
    perl -le 'print scalar localtime $ARGV[0]' $1
}

function lt() { ls -ltrsa "$@" | tail; }
function psgrep() { ps -er | grep -v grep | grep "$@" -i --color=auto; }
function ffind() { find . -iname "*$@*"; }
