#!/bin/bash

# Cribbed from here:
# http://mediadoneright.com/content/ultimate-git-ps1-bash-prompt

if [ ! -e ~/.git-completion.bash ]; then
    echo "Where is git completion?  Bailing out!"
    return 1
fi

# confirmed its there -- source it and go!
. ~/.git-completion.bash

###################################################

#  Customize BASH PS1 prompt to show current GIT repository and branch.
#  by Mike Stewart - http://MediaDoneRight.com

#  SETUP CONSTANTS
#  Bunch-o-predefined colors.  Makes reading code easier than escape sequences.
#  I don't remember where I found this.  o_O

# Reset
Color_Off="\[\033[0m\]"       # Text Reset

# Regular Colors
Black="\[\033[0;30m\]"        # Black
Red="\[\033[0;31m\]"          # Red
Green="\[\033[0;32m\]"        # Green
Yellow="\[\033[0;33m\]"       # Yellow
Blue="\[\033[0;34m\]"         # Blue
Purple="\[\033[0;35m\]"       # Purple
Cyan="\[\033[0;36m\]"         # Cyan
White="\[\033[0;37m\]"        # White

# Bold
BBlack="\[\033[1;30m\]"       # Black
BRed="\[\033[1;31m\]"         # Red
BGreen="\[\033[1;32m\]"       # Green
BYellow="\[\033[1;33m\]"      # Yellow
BBlue="\[\033[1;34m\]"        # Blue
BPurple="\[\033[1;35m\]"      # Purple
BCyan="\[\033[1;36m\]"        # Cyan
BWhite="\[\033[1;37m\]"       # White

# Underline
UBlack="\[\033[4;30m\]"       # Black
URed="\[\033[4;31m\]"         # Red
UGreen="\[\033[4;32m\]"       # Green
UYellow="\[\033[4;33m\]"      # Yellow
UBlue="\[\033[4;34m\]"        # Blue
UPurple="\[\033[4;35m\]"      # Purple
UCyan="\[\033[4;36m\]"        # Cyan
UWhite="\[\033[4;37m\]"       # White

# Background
On_Black="\[\033[40m\]"       # Black
On_Red="\[\033[41m\]"         # Red
On_Green="\[\033[42m\]"       # Green
On_Yellow="\[\033[43m\]"      # Yellow
On_Blue="\[\033[44m\]"        # Blue
On_Purple="\[\033[45m\]"      # Purple
On_Cyan="\[\033[46m\]"        # Cyan
On_White="\[\033[47m\]"       # White

# High Intensty
IBlack="\[\033[0;90m\]"       # Black
IRed="\[\033[0;91m\]"         # Red
IGreen="\[\033[0;92m\]"       # Green
IYellow="\[\033[0;93m\]"      # Yellow
IBlue="\[\033[0;94m\]"        # Blue
IPurple="\[\033[0;95m\]"      # Purple
ICyan="\[\033[0;96m\]"        # Cyan
IWhite="\[\033[0;97m\]"       # White

# Bold High Intensty
BIBlack="\[\033[1;90m\]"      # Black
BIRed="\[\033[1;91m\]"        # Red
BIGreen="\[\033[1;92m\]"      # Green
BIYellow="\[\033[1;93m\]"     # Yellow
BIBlue="\[\033[1;94m\]"       # Blue
BIPurple="\[\033[1;95m\]"     # Purple
BICyan="\[\033[1;96m\]"       # Cyan
BIWhite="\[\033[1;97m\]"      # White

# High Intensty backgrounds
On_IBlack="\[\033[0;100m\]"   # Black
On_IRed="\[\033[0;101m\]"     # Red
On_IGreen="\[\033[0;102m\]"   # Green
On_IYellow="\[\033[0;103m\]"  # Yellow
On_IBlue="\[\033[0;104m\]"    # Blue
On_IPurple="\[\033[10;95m\]"  # Purple
On_ICyan="\[\033[0;106m\]"    # Cyan
On_IWhite="\[\033[0;107m\]"   # White

# Various variables you might want for your PS1 prompt instead
Time12h="\T"
Time12a="\@"
PathShort="\W"
PathFull="\w"
NewLine="\n"
Jobs="\j"



function stoppedjobs {
    j=`jobs -s | wc -l | sed -e "s/ //g"`
    if [[ $j -ne 0 ]]; then
        echo -n "[$j]"
    fi
}

function currentvirtenv {
    ve=`basename "\$VIRTUAL_ENV"`
    if [[ $ve != "" ]]; then
        echo -n " [$ve]"
    fi
}

function priorrc {
    if [[ $prior -ne 0 ]]; then
        echo -n " [$prior]"
    fi
}

function save_returncode {
    prior=$?
}

# needs to be the first one in the prompt command
export PROMPT_COMMAND="save_returncode${PROMPT_COMMAND+;}$PROMPT_COMMAND"

function timer_start {
    timer=${timer:-$SECONDS}
}

function timer_stop {
    elapsed=$(($SECONDS - $timer))
    if [[ $elapsed < 5 ]]; then
        timer_show=""
    else
        timer_show=" ${elapsed}s"
    fi
    unset timer
}

# Display host and title in menu bar
case ${TERM} in
    xterm*|rxvt*|Eterm|aterm|kterm|gnome*|interix)
        PROMPT_COMMAND=${PROMPT_COMMAND}${PROMPT_COMMAND+;}'echo -ne "\033]0;${TITLE}${TITLE+  }${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}$(currentvirtenv)\007"'
        use_color=true
    ;;
    screen)
        PROMPT_COMMAND=${PROMPT_COMMAND}${PROMPT_COMMAND+;}'echo -ne "\033_${TITLE}${TITLE+  }${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}$(currentvirtenv)\033\\"'
        use_color=true
        ;;
esac

trap 'timer_start' DEBUG
export PROMPT_COMMAND="$PROMPT_COMMAND${PROMPT_COMMAND+;}timer_stop"

export PS1="$Yellow\${USER}$(stoppedjobs)\${timer_show}$Purple\$(priorrc)$Color_Off"'$(git branch &>/dev/null;\
if [ $? -eq 0 ]; then \
  echo "$(echo `git status` | grep "nothing to commit" > /dev/null 2>&1; \
  if [ "$?" -eq "0" ]; then \
    # @4 - Clean repository - nothing to commit
    echo "'$Green'"$(__git_ps1 " (%s)"); \
  else \
    # @5 - Changes to working tree
    echo "'$IRed'"$(__git_ps1 " {%s}"); \
  fi)"; \
fi)'" $Yellow$PathShort>$Color_Off "

# tell virtualenv not to insert itself at the beginning of the prompt, since 
# I'm taking care of that now
export VIRTUAL_ENV_DISABLE_PROMPT=1

