#!/bin/bash

if [ -e /usr/local/bin/virtualenvwrapper.sh ]; then
    # virtualenvwrapper setup (feel free to change project directories)
    export WORKON_HOME=$HOME/.virtualenv
    export PROJECT_HOME=~/src
    export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
    export VIRTUALENVWRAPPER_VIRTUALENV=`which virtualenv`
    source /usr/local/bin/virtualenvwrapper.sh
fi

test_and_source ~/.rvm/scripts/rvm
