#!/bin/bash

export rabbit='launchctl load ~/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist'

if [ -e /usr/local/bin/virtualenvwrapper.sh ]; then
    # virtualenvwrapper setup (feel free to change project directories)
    export WORKON_HOME=$HOME/.virtualenv
    export PROJECT_HOME=~/src
    export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
    export VIRTUALENVWRAPPER_VIRTUALENV=`which virtualenv`
    source /usr/local/bin/virtualenvwrapper.sh
fi

test_and_source ~/.rvm/scripts/rvm


function edxprod {
    multitail -s 2  \
        --config /usr/local/etc/multitail.conf \
        -CS apache \
        -l 'ssh app10.prod.class.stanford.edu "tail -f /logs/nginx/access.log"' \
        -l 'ssh app11.prod.class.stanford.edu "tail -f /logs/nginx/access.log"' \
        -l 'ssh app20.prod.class.stanford.edu "tail -f /logs/nginx/access.log"' \
        -l 'ssh app21.prod.class.stanford.edu "tail -f /logs/nginx/access.log"' \
        -CS apache_error \
        -l 'ssh app10.prod.class.stanford.edu "tail -f /logs/nginx/error.log"' \
        -l 'ssh app11.prod.class.stanford.edu "tail -f /logs/nginx/error.log"' \
        -l 'ssh app20.prod.class.stanford.edu "tail -f /logs/nginx/error.log"' \
        -l 'ssh app21.prod.class.stanford.edu "tail -f /logs/nginx/error.log"' 
}



